# Configuration file for Prettier. See https://prettier.io/docs/en/options

# The following should be handled when displaying, not when writing text.
useTabs: true # Tabs are made for indentation, spaces are a hack.
proseWrap: never
printWidth: 256 # Shouldn't be limited, but realistically 256 won't be exceeded.

trailingComma: all # Avoids unnecessary diffs when adding new items.
